name: trading-simulator

services:
  postgres:
    image: postgres:16
    container_name: trading-simulator-db
    restart: always
    environment:
      POSTGRES_DB: trading_simulator
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    command: postgres -c listen_addresses='*'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    container_name: trading-simulator-backend
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/trading_simulator
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    container_name: trading-simulator-frontend
    depends_on:
      - backend
    ports:
      - "80:80"

volumes:
  postgres_data:
